#+TITLE: dotfiles
#+AUTHOR: Tenn1518

Configuration files for programs such as emacs, zsh, etc to bootstrap onto a UNIX-like operating system.

This project is licensed under the terms of the [[https://github.com/Tenn1518/dotfiles/blob/master/LICENSE][MIT license]].

** Prerequisites

Linux: ~Light~ (tool to change backlight)
macOS: ~Homebrew~
\*: ~emacs~, ~zsh~, ~alacritty~, Dracula themes for as many things as possible, and the Iosevka family of fonts

** How to Install

Install the dotfiles with:
#+BEGIN_EXAMPLE
$ git clone --recursive https://github.com/Tenn1518/dotfiles ~/.dotfiles
$ cd ~/.dotfiles
$ ./install.py
#+END_EXAMPLE

This will symlink folders and files from their respective locations in $HOME to under ~/.dotfiles

Upon entering emacs, run ~M-x all-the-icons-install-fonts~. This will install icon fonts not only for emacs, but also for ~waybar~.

** What's included?

| Program | Description                                                                                          |
|---------+------------------------------------------------------------------------------------------------------|
| emacs   | Text editor/IDE/operating system with my personal configuration with a hefty amount of vim bindings. |
| Sway    | i3 but on Wayland.                                                                                   |
| Waybar  | Bar displaying information and workspaces in SwayWM.                                                 |
| rofi    | Dmenu alternative that works better with Sway and Wayland.                                           |
| neovim  | Legacy configuration from before I started using emacs. Not maintained or useful.                    |
